kind: Deployment
apiVersion: apps/v1
metadata:
  name: ca-cli
  labels:
    app: blockchain
    role: ca-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
      role: ca-cli
  template:
    metadata:
      labels:
        app: blockchain
        role: ca-cli
    spec:
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name: ca-cli
          image: hyperledger/fabric-ca:1.4.9
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca-cli-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/priv_sk
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: CRYPTO_HOME # custom env. variable
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
          ports:
            - containerPort: 7054
          volumeMounts:
            - name: nfs
              mountPath: /etc/hyperledger/fabric-ca-server-config
              subPath: crypto-config/externalServices/ca-cli/
            - name: nfs
              mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
              subPath: crypto-config/
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","rm -rf /etc/hyperledger/fabric-ca-server-config/* /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/*"]