apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  labels:
    app: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
      containers:
      - name: cli
        image: hyperledger/fabric-tools:2.4.6
        tty: true
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        args:
          - /bin/bash
        env:
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: CORE_PEER_ID
            value: cli
          - name: CORE_PEER_ADDRESS
            value: TODO
          - name: CORE_PEER_LOCALMSPID
            value: TODO
          - name: CORE_CHAINCODE_KEEPALIVE
            value: TODO
          - name: CORE_PEER_TLS_ENABLED
            value: TODO
          - name: CORE_PEER_TLS_CERT_FILE
            value: TODO
          - name: CORE_PEER_TLS_KEY_FILE
            value: TODO
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: TODO
          - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
            value: TODO
          - name: CORE_PEER_TLS_CLIENTROOTCAS_FILES
            value: TODO
          - name: CORE_PEER_TLS_CLIENTCERT_FILE
            value: TODO
          - name: CORE_PEER_TLS_CLIENTKEY_FILE
            value: TODO
          - name: CORE_PEER_MSPCONFIGPATH
            value: TODO
          - name: ORDERER_TLS_CA
            value: TODO
        volumeMounts:
          - name: nfs
            mountPath: /opt/gopath/src/github.com/chaincode
            subPath: chaincodes/
          - name: nfs
            mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            subPath: crypto-config/
          - name: nfs
            mountPath: /etc/hyperledger/configtx
            subPath: config/
