kind: Service
apiVersion: v1
metadata:
  name: ca-org1
spec:
  selector:
    app: blockchain
    role: ca-org1
  ports:
    - name: tcp-7054
      port: 7054
      protocol: TCP

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ca-org1
  labels:
    app: blockchain
    role: ca-org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
      role: ca-org1
  template:
    metadata:
      labels:
        app: blockchain
        role: ca-org1
    spec:
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name: ca-org1
          image: hyperledger/fabric-ca:1.4.9
          args:
            - sh
            - -c
            - fabric-ca-server start -b admin:adminpw -d --csr.hosts 'ca-org1' --csr.cn 'ca-org1'
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca-org1-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/priv_sk
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-org1
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
          ports:
            - containerPort: 7054
          volumeMounts:
            - name: nfs
              mountPath: /etc/hyperledger/fabric-ca-server-config
              subPath: crypto-config/peerOrganizations/org1/ca/
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","rm -rf /etc/hyperledger/fabric-ca-server-config/*"]